# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: PR maintenance

on:
  pull_request:
    branches: [ "master" ]
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v6
      - run: npm ci
      - run: npm run-script full-check
